### Python Pandas Sorting

In [1]:
import pandas as pd
import numpy as np

### create a numpy array

In [2]:
data_ar1=np.array([4,5,6,7])

In [4]:
data_ar2 = np.array([[4,5,6],[7,8,9]])

###  Sort 1D array in Pandas

In [5]:
data_ar3 = np.array([5,7,9])
data_ar3.sort()
data_ar3

array([5, 7, 9])

In [8]:
data_ar4=np.array([[9,8],[11,0]])
data_ar4.sort(axis = 0)
data_ar4


array([[ 9,  0],
       [11,  8]])

In [9]:
data_ar4.sort(axis = 1)
data_ar4

array([[ 0,  9],
       [ 8, 11]])

### Sort a Series with Pandas
#### Creating a Series in Pandas

In [11]:
data_se = pd.Series([np.nan, 3, 7, 11, 8])

### Sort a Series in Pandas
#### Sorting a Pandas Series in an ascending order

In [12]:
data_se.sort_values(ascending = True)

1     3.0
2     7.0
4     8.0
3    11.0
0     NaN
dtype: float64

#### Sorting a Pandas Series in a descending order

In [13]:
data_se.sort_values(ascending = False )

3    11.0
4     8.0
2     7.0
1     3.0
0     NaN
dtype: float64

####  Sorting values inplace

In [14]:
data_se.sort_values(ascending=False, inplace=True)
data_se

3    11.0
4     8.0
2     7.0
1     3.0
0     NaN
dtype: float64

#### Sorting values while putting Na first


In [15]:
data_se.sort_values(na_position = 'first')


0     NaN
1     3.0
2     7.0
4     8.0
3    11.0
dtype: float64

### Sort a DataFrame with Pandas
####  Creating a DataFrame in Pandas

In [17]:
data_df1 = pd.DataFrame({'col1' : [5, 2, 5, 2, 2, 1],'col2' : ['C', 'B', 'A', np.nan, 'C', 'D'],'col3': [9, 6, 0, 7, 5, 8]})
data_df1

col1 col2  col3
0     5    C     9
1     2    B     6
2     5    A     0
3     2  NaN     7
4     2    C     5
5     1    D     8

### Sorting the DataFrame
####  Sort Pandas DataFrames in Ascending Order

In [19]:
data_df1.sort_values(by=['col1'])

col1 col2  col3
5     1    D     8
1     2    B     6
3     2  NaN     7
4     2    C     5
0     5    C     9
2     5    A     0

In [20]:
data_df1.sort_values(by=['col1', 'col2'])

col1 col2  col3
5     1    D     8
1     2    B     6
4     2    C     5
3     2  NaN     7
2     5    A     0
0     5    C     9

### Sort Pandas in Descending Order

In [21]:
data_df1.sort_values(by='col1', ascending=False)

col1 col2  col3
0     5    C     9
2     5    A     0
1     2    B     6
3     2  NaN     7
4     2    C     5
5     1    D     8

In [22]:
data_df1.sort_values(by=['col1', 'col2'], ascending=False)

col1 col2  col3
0     5    C     9
2     5    A     0
4     2    C     5
1     2    B     6
3     2  NaN     7
5     1    D     8

### Sorting while putting Na first

In [23]:
data_df1.sort_values(by='col2', ascending=False, na_position='first')

col1 col2  col3
3     2  NaN     7
5     1    D     8
0     5    C     9
4     2    C     5
1     2    B     6
2     5    A     0

### Sort Pandas DataFrames by Index

In [24]:
data_df1 = pd.DataFrame({'col3' : [9, 6, 0, 7, 5, 8],'col1' : ['C', 'B', 'A', np.nan, 'C', 'D'],'col2': [20, 3, 5, 18, 15,1]})
data_df1

col3 col1  col2
0     9    C    20
1     6    B     3
2     0    A     5
3     7  NaN    18
4     5    C    15
5     8    D     1

In [25]:
data_df1.sort_index(axis = 1,inplace = True)
data_df1

col1  col2  col3
0    C    20     9
1    B     3     6
2    A     5     0
3  NaN    18     7
4    C    15     5
5    D     1     8

### Sort Pandas DataFrames are by Column name

In [26]:
L = ['col3','col1','col2']
data_df1=data_df1[L]
data_df1

col3 col1  col2
0     9    C    20
1     6    B     3
2     0    A     5
3     7  NaN    18
4     5    C    15
5     8    D     1

In [28]:
data_df1 = data_df1.reindex(sorted(data_df1.columns), axis=1)
data_df1

col1  col2  col3
0    C    20     9
1    B     3     6
2    A     5     0
3  NaN    18     7
4    C    15     5
5    D     1     8

### Sort Pandas DataFrames by Rows

In [30]:
data_df1 = pd.DataFrame({'col3' : [4,8,7,9,3,5],'col1' : [14,18,27,29,6,1],'col2': [3,6,9,2,4,8]},index=['A','B','C','D','E','F'])
data_df1

col3  col1  col2
A     4    14     3
B     8    18     6
C     7    27     9
D     9    29     2
E     3     6     4
F     5     1     8

In [33]:
data_df1 = data_df1.sort_values(by='D', axis=1)
data_df1

col2  col3  col1
A     3     4    14
B     6     8    18
C     9     7    27
D     2     9    29
E     4     3     6
F     8     5     1